---
title: ""
---

```{r, warning=F, message=F, error=F, echo = F}
pacman::p_load(blogdown, shiny, shiny.semantic, dplyr, purrr)
```


<div class = "ui text container">

<!--<h1 class="ui header">
  <div class="content">
    Slides
  </div>
</h1> -->

```{r, echo = F, eval = F}
slides <- list(
  first = tibble::tibble(
    title = "DECODING THE ALT-RIGHT",
    image_primary = "slides/altright_concept.png", 
    image_secondary = "slides/altright_model.png",
    location = "VOX-Pol Conference Amsterdam",
    year = "2018",
    link = "https://decoding-the-altright.netlify.com/#1"
  )
  # second = tibble::tibble(
  #   title = "Some other",
  #   image_primary = "slides/circle-construction-icon.svg", 
  #   image_secondary = "images/",
  #   location = ""
  # )
)



div(class="ui two stackable link cards",
slides %>% 
  map(~{
      a(class="card", href=.x$link, target="_blank", rel="nofollow",
        div(class="ui fade reveal image",
          shiny::tags$img(class="visible content", src=.x$image_primary),
          shiny::tags$img(class="hidden content", src=.x$image_secondary)
        ),
        div(class="extra",
          h3(class = "ui header",
            div(class="content",
              .x$title,
              div(class="meta",
                .x$location, " ", .x$year
              )
            )
          )
        )
      ) 
  })
)
```
</div>


<br>
<br>
<br>

<!--<div class="ui stackable three column grid container">
  <div class="column">
  <h2 class="ui icon header">
  <i class="code icon"></i>
  <div class="content">
  Web Development
  <div class="sub header">
  This website is ⚡ by Hugo, Blogdown, Rmarkdown and Semantic UI 
  </div>
  </div>
  </h2>
  </div>
  <div class="column">
  <h2 class="ui icon header">
  <i class="language icon"></i>
  <div class="content">
  Text Mining
  <div class="sub header">
  I enjoy web scraping and working unstructured data. Natural Language Processing offers powerful learners for text predictions like word2vec, LSTMs or Convolutional Neural Networks.
  </div>
  </div>
  </h2>
  </div>
  <div class="column">
  <h2 class="ui icon header">
  <i class="flask icon"></i>
  <div class="content">
  Social Sciences
  <div class="sub header">
  Combining interesting research questions about human behavoir and decisions with statistics and machine learning is never boring but enlightening.
  </div>
  </div>
  </h2>
  </div>
</div>

<br>
<div class="ui divider"></div>
<br>-->

